version: "3.9"
services:
  postgres:
    image: postgres:15.3
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=2654
      - POSTGRES_DB=simple_bank_db
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:2654@postgres:5432/simple_bank_db?sslmode=disable
    depends_on:
      - postgres
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]