### create user
POST http://127.0.0.1:8080/users/login
Content-Type: application/json
Accept: application/json

{
    "username": "riad56",
    "password": "123456"
}

### create user
POST http://127.0.0.1:8080/users/
Content-Type: application/json
Accept: application/json

{
    "username": "riad56",
    "full_name": "Riadul Islam",
    "email": "riad56@gmail.com",
    "password": "123456"
}

### get account list
GET http://127.0.0.1:8080/accounts?page_id=1&page_size=10
Content-Type: application/json
Accept: application/json

### get account by id
GET http://127.0.0.1:8080/accounts/205
Content-Type: application/json
Accept: application/json

### create account
POST http://127.0.0.1:8080/accounts/
Content-Type: application/json
Accept: application/json

{
    "Owner": "gxifdg",
    "Currency": "USD"
}

### create transfers
POST http://127.0.0.1:8080/transfers/
Content-Type: application/json
Accept: application/json

{
    "from_account_id": 1,
    "to_account_id": 2,
    "amount": 10,
    "Currency": "CAD"
}